<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Registration Certificate</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; margin: 0; padding: 0; }
        .certificate-container {
            border: 15px solid #001f3f; /* Navy Blue Border */
            padding: 30px;
            position: relative;
            background: #fff;
        }
        .inner-border {
            border: 2px solid #D4AF37; /* Gold Inner Line */
            padding: 40px;
        }
        .header { text-align: center; }
        .header h1 { 
            color: #001f3f; 
            text-transform: uppercase; 
            letter-spacing: 5px; 
            margin-bottom: 0;
        }
        .header h3 { color: #FF5C5C; margin-top: 5px; } /* Light Red accent */
        
        .content { margin-top: 50px; text-align: center; }
        .matricule-box {
            display: inline-block;
            background-color: #001f3f;
            color: #D4AF37; /* Gold Text */
            padding: 10px 25px;
            font-size: 24px;
            font-weight: bold;
            border-radius: 5px;
            margin: 20px 0;
        }
        .details-table {
            width: 100%;
            margin-top: 30px;
            border-collapse: collapse;
        }
        .details-table td {
            padding: 10px;
            border-bottom: 1px solid #eee;
        }
        .label { font-weight: bold; color: #001f3f; width: 30%; text-align: right; }
        .value { text-align: left; padding-left: 20px; }
        
        .footer {
            margin-top: 60px;
            text-align: center;
            font-size: 12px;
            color: #777;
        }
        .watermark {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 100px;
            color: rgba(255, 92, 92, 0.1); /* Very faded Light Red */
            z-index: -1;
        }
    </style>
</head>
<body>
    <div class="certificate-container">
        <div class="inner-border">
            <div class="watermark">OFFICIAL</div>
            
            <div class="header">
                <h1>Certificate of Registry</h1>
                <h3>Super Admin Establishment Verification</h3>
            </div>

            <div class="content">
                <p>This is to certify that the establishment known as</p>
                <h2 style="color: #001f3f;">{{ $restaurant->name }}</h2>
                
                <p>has been officially registered under the category of <strong>{{ $restaurant->category }}</strong>.</p>
                
                <div class="matricule-box">
                    MATRICULE: {{ $restaurant->matricule }}
                </div>

                <table class="details-table">
                    <tr>
                        <td class="label">Owner Name:</td>
                        <td class="value">{{ $restaurant->owner_name }}</td>
                    </tr>
                    <tr>
                        <td class="label">Location:</td>
                        <td class="value">{{ $restaurant->location }}</td>
                    </tr>
                    <tr>
                        <td class="label">Registration Date:</td>
                        <td class="value">{{ now()->format('F d, Y') }}</td>
                    </tr>
                </table>
            </div>

            <div class="footer">
                <p>Generated by the Empire Administrative System</p>
                <div style="height: 2px; background: #D4AF37; width: 100px; margin: 10px auto;"></div>
            </div>
        </div>
    </div>
</body>
</html>